export const Lookups_API={
  "matterCategory":{
    "get":"LawMtrCat/GetList",
    "create":"LawMtrCat/Create",
    "update":"LawMtrCat/Update",
    "delete":"LawMtrCat/Delete"

  },
  "matterCategoryType":{
    "get":"LawMtrTyp/GetList",
    "create":"LawMtrTyp/Create",
    "update":"LawMtrTyp/Update",
    "delete":"LawMtrTyp/Delete"
  },
  "jurisdictions":{
    "get":"Law_Jurisdiction/GetList",
    "create":"Law_Jurisdiction/Create",
    "update":"Law_Jurisdiction/Update",
    "delete":"Law_Jurisdiction/Delete"

  },
  "judicature":{
    "get":"Law_Judicature/GetList",
    "create":"Law_Judicature/Create",
    "update":"Law_Judicature/Update",
    "delete":"Law_Judicature/Delete"

  },
  "practiceArea":{
    "get":"Law_PractsArea/GetList",
    "create":"Law_PractsArea/Create",
    "update":"Law_PractsArea/Update",
    "delete":"Law_PractsArea/Delete"
  },
  "clientGroup":{
    "get":"ClientGroup/GetList",
    "create":"ClientGroup/Create",
    "update":"ClientGroup/Update",
    "delete":"ClientGroup/Delete",
    
  },
  "department":{
    "get":"Law_Department/GetList",
    "create":"Law_Department/Create",
    "update":"Law_Department/Update",
    "delete":"Law_Department/Delete"
  },
  "industry":{
    "get":"Law_Industry/GetList",
    "create":"Law_Industry/Create",
    "update":"Law_Industry/Update",
    "delete":"Law_Industry/Delete"
  },
  "mattStatus":{
    "get":"Law_MattStatus/GetList",
    "create":"Law_MattStatus/Create",
    "update":"Law_MattStatus/Update",
    "delete":"Law_MattStatus/Delete"
  },
  "referralType":{
    "get":"Law_ReferralType/GetList",
    "create":"Law_ReferralType/Create",
    "update":"Law_ReferralType/Update",
    "delete":"Law_ReferralType/Delete"
  },
  "adjournmentReasons":{
    "get":"Law_AdjournmentReasons/GetList",
    "create":"Law_AdjournmentReasons/Create",
    "update":"Law_AdjournmentReasons/Update",
    "delete":"Law_AdjournmentReasons/Delete"
  },
  "partiesDescription":{
    "get":"Law_PartiesDescription/GetList",
    "create":"Law_PartiesDescription/Create",
    "update":"Law_PartiesDescription/Update",
    "delete":"Law_PartiesDescription/Delete"
  },
  "stage":{
    "get":"Law_Stage/GetList",
    "create":"Law_Stage/Create",
    "update":"Law_Stage/Update",
    "delete":"Law_Stage/Delete"
  },
  "taskCode":{
    "get":"Law_TaskCode/GetList",
    "create":"Law_TaskCode/Create",
    "update":"Law_TaskCode/Update",
    "delete":"Law_TaskCode/Delete"
  },
  "rateType":{
    "get":"Law_RateType/GetList",
    "create":"Law_RateType/Create",
    "update":"Law_RateType/Update",
    "delete":"Law_RateType/Delete"
    
  },
  "rate":{
    "get":"Law_Rate/GetList",
    "create":"Law_Rate/Create",
    "update":"Law_Rate/Update",
    "delete":"Law_Rate/Delete"
    
  },
  "branch":{
    "get":"Law_Branch/GetList",
    "create":"Law_Branch/Create",
    "update":"Law_Branch/Update",
    "delete":"Law_Branch/Delete"
    
  },

}
